spring:
  messages:
    # 语言文件路径
    basename: i18n/messages
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  # Redis配置
  redis:
    # 是否使用redis替换内存缓存
    enabled: false
    host: 127.0.0.1
    port: 6379
  # 数据库总配置
  datasource:
    # 数据源类型选择
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      # 数据库每个连接池的配置信息
      druid:
        # 初始化大小
        initial-size: 10
        # 最小存留数
        min-idle: 10
        # 最大连接数
        maxActive: 200
        # 配置获取连接等待超时的时间，单位是毫秒
        maxWait: 30000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 30000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000

server:
  port: 8080

# 基础日志配置
logging:
  # 日志记录等级
  level:
    idea.verlif.justdata: DEBUG

just-data:
  # SQL配置
  sql:
    # 是否输出到控制台（true - 输出到控制台；false - 不输出）
    print: true
  # 接口日志处理
  api-log:
    # 日志类型（FILE - 写入文件；CONSOLE - 输出到控制台；XML - 通过xml配置写入数据库）（启用多个类型以“,”隔开，置为空则不启用接口日志）
    type: FILE, XML
    # 日志文件配置
    file:
      # 当日志类型为FILE时生效，表示写入的文件路径
      log: log\api-log.log
      # 当日志类型为XML时生效，表示读取的XML配置文件的路径
      xml: src\test\java\resources\log\log.xml
  # Token配置
  token:
    # 解析的请求header参数名
    header: Token
    # Token生成使用的密钥
    secret: qwertyuioplkjhgfdsazxcvbnm
    # Token有效期，也表示了登录token空闲时的存活时间。单位为秒
    expireTime: 3600
  # 操作项配置
  items:
    # 操作项配置文件路径
    path: src\test\java\resources\one
  # 接口异常配置
  exception:
    # 接口异常输出方式（CONSOLE - 控制台；FILE - 独立文件；CLIENT - 客户端），多个方式以“,”隔开
    output: CONSOLE
    # 当output中存在FILE时生效
    file: log\exception.log
  # 文件系统配置
  file:
    # 是否开启文件系统
    enabled: true
    # 使用文件系统时是否需要登录
    needOnline: false
    # 文件上传模式，决定了上传文件的存储模式（DAY - 按照日期建立文件夹；MONTH - 按照月份建立文件夹；ID - 根据登录用户ID建立文件夹）
    uploadType: ID
    # 文件操作模式，控制用户的文件管理权限（ID - 只允许用户操作自己的ID文件域文件，配合uploadType(ID)使用；ALL - 无限制）
    downloadType: ID
  # 登录配置
  login:
    # 登录配置的xml地址
    file: src\test\java\resources\login.xml
  # 权限服务配置
  permission:
    # 权限配置的xml地址
    file: src\test\java\resources\permission.xml

# Station配置
station:
  # 文件配置
  file:
    # 是否允许新上传的文件覆盖已有的同名文件。false则上传同名文件会被拒绝。
    cover: false
    # 文件上传路径
    path:
      # 文件系统根目录，相对路径或绝对路径
      main: F:/upload