spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      # 连接池的配置信息
      druid:
        # 初始化大小，最小，最大
        initial-size: 10
        min-idle: 10
        maxActive: 200
        # 配置获取连接等待超时的时间，单位是毫秒
        maxWait: 30000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 30000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    idea.verlif.justdata: DEBUG

just-data:
  items:
    path: src\test\java\resources\envo
  exception:
    file: log\exception.log
  login:
    enable: true
    queryUserKey:
      label: demo
      sql: "SELECT user_password FROM t_user WHERE id = @{id}"
  permission:
    enable: true
    inner-permission: admin
    queryPermission:
      label: demo
      sql: "SELECT permission
        FROM t_permission p
        LEFT JOIN t_role_permission rp ON rp.permission_id = p.permission_id
        LEFT JOIN t_user_role ur ON ur.role_id = rp.role_id
        WHERE ur.user_id = ${userId}"

station:
  api-log:
    pool-info:
      enable: true
      # 日志线程池最大线程数
      max: 200
      # 日志等待队列长度
      length: 1000