spring:
  messages:
    # 语言文件路径
    basename: i18n/messages
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  # Redis配置
  redis:
    # 是否使用redis替换内存缓存
    enabled: true
    host: 127.0.0.1
    port: 6379
  # 数据库总配置
  datasource:
    # 数据源类型选择
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      # 数据库每个连接池的配置信息
      druid:
        # 初始化大小
        initial-size: 10
        # 最小存留数
        min-idle: 10
        # 最大连接数
        maxActive: 200
        # 配置获取连接等待超时的时间，单位是毫秒
        maxWait: 30000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 30000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000

# 基础日志配置
logging:
  # 日志记录等级
  level:
    idea.verlif.justdata: DEBUG

just-data:
  # Token配置
  token:
    # 解析的请求header参数名
    header: Token
    # Token生成使用的密钥
    secret: qwertyuioplkjhgfdsazxcvbnm
    # Token有效期，也表示了登录token空闲时的存活时间。单位为秒
    expireTime: 3600
  # 操作项配置
  items:
    # 操作项配置文件路径
    path: src\test\java\resources\one
  # 接口异常配置
  exception:
    # 接口异常输出方式（CONSOLE - 控制台；FILE - 独立文件；CLIENT - 客户端），多个方式以“,”隔开
    output: CONSOLE
    # 当output中存在FILE时生效
    file: log\exception.log
  # 文件系统配置
  file:
    # 是否开启文件系统
    enabled: true
    # 使用文件系统时是否需要登录
    needOnline: false
    # 文件上传模式，决定了上传文件的存储模式（DAY - 按照日期建立文件夹；MONTH - 按照月份建立文件夹；ID - 根据登录用户ID建立文件夹）
    uploadType: ID
    # 文件操作模式，控制用户的文件管理权限（ID - 只允许用户操作自己的ID文件域文件，配合uploadType(ID)使用；ALL - 无限制）
    downloadType: ID
  # 登录配置
  login:
    # 登录配置的xml地址
    file: src\test\java\resources\login.xml
  # 权限服务配置
  permission:
    # 权限配置的xml地址
    file: src\test\java\resources\permission.xml

# Station配置
station:
  # 接口日志
  api-log:
    # 接口日志线程信息
    pool-info:
      # 是否以后台线程方式运行接口日志服务
      enable: true
      # 日志线程池最大线程数
      max: 200
      # 日志等待队列长度
      length: 1000
  # 文件配置
  file:
    # 是否允许新上传的文件覆盖已有的同名文件。false则上传同名文件会被拒绝。
    cover: false
    # 文件上传路径
    path:
      # 文件系统根目录，相对路径或绝对路径
      main: F:/upload