spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    url: jdbc:mysql://gz-cynosdbmysql-grp-dxzq6on3.sql.tencentcdb.com:20273/test?useSSL=false&useUnicode=true&serverTimezone=Hongkong&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: ac16508...
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    idea.verlif.justdata: DEBUG

route:
  path: D:\Code\Java\just-data